### ISSUE TITLE
Change "gptme-python" to just "gptme" on pypi

### ISSUE THREAD

**Issue by brayo-pip** [ErikBjare/gptme#148]
It's a way more unique and if someone was to register a package on pypi with that name it would be not the greatest user experience. The name is still open so you can at least grab as you consider making the change.

**Comment by ErikBjare** [comment]
Unfortunately the `gptme` package name is reserved on PyPi, due to similarity to another package name, so it cannot actually be registered as a package.

**Comment by ErikBjare** [comment]
Looks like it's like due to the existence of the very similarly named gpt-me package: https://pypi.org/project/gpt-me/

Could DM the author @TKDKid1000 and [ask them to transfer](https://peps.python.org/pep-0541/#how-to-request-a-name-transfer) the gptme name, if they are no longer interested in it (no recent releases, stuck at v0.1.0).

**Comment by ErikBjare** [comment]
I'll reopen this and try nicely asking the author via DM.

**Comment by ErikBjare** [comment]
He replied and graciously handed over the name!

Now you can simply `pip install gptme` :star_struck:
