### ISSUE TITLE
Google Gemini

### ISSUE THREAD

**Issue by egoran2** [ErikBjare/gptme#161]
Hello, any ways to use gemini api as provider? 
Thank you

**Comment by ErikBjare** [comment]
Only via OpenRouter at the moment.

I won't implement first-party support anytime soon, but will accept contributions.

**Comment by lloydchang** [comment]
Relates to https://github.com/ErikBjare/gptme/pull/272

**Comment by lloydchang** [comment]
Hi @egoran2,

When you find time, please test the following steps on your computer?

1. Clone the repository:
   ```
   gh repo clone ErikBjare/gptme
   ```

2. Navigate to the project directory:
   ```
   cd gptme
   ```

3. Check out the pull request:
   ```
   gh pr checkout 272 --repo ErikBjare/gptme
   ```

4. Create a virtual environment:
   ```
   python -m venv venv
   ```

5. Activate the virtual environment:
   ```
   source ./venv/bin/activate
   ```

6. Install the required dependencies using Poetry:
   ```
   poetry install
   ```

7. Run gptme:
   ```
   gptme
   ```

After following these steps, gptme should prompt you with:

> New conversation or load previous?

- Select "New conversation" and press the "Return" key.

Next, `gptme` should prompt you with:

> No API key set for OpenAI, Anthropic, OpenRouter, or Gemini.
> You can get one at:
>  - OpenAI: https://platform.openai.com/account/api-keys
>  - Anthropic: https://console.anthropic.com/settings/keys
>  - OpenRouter: https://openrouter.ai/settings/keys
>  - Gemini: https://aistudio.google.com/app/apikey
> 
> Your OpenAI, Anthropic, OpenRouter, or Gemini API key:

If the `GEMINI_API_KEY` environment variable is already defined, `gptme` will use that variable's value instead.

These installation instructions uses pull request https://github.com/ErikBjare/gptme/issues/272 because a newer version of `gptme` (greater than 0.24.0) has not been released yet.

In the meantime, running `gptme --version` will still show version 0.24.0, regardless of which variant you use:

- Variant A: Installed via `pipx install gptme` without Gemini support
- Variant B: Installed via `source ./venv/bin/activate && poetry install` with Gemini support

To differentiate between the two variants of the same version (0.24.0), please follow the above instructions until a newer version of `gptme` is released.

I hope this helps!

Thanks!
