### ISSUE TITLE
browser tool not available despite playwright being installed

### ISSUE THREAD

**Issue by materemias** [ErikBjare/gptme#191]
Hi,

thanks for the awesome tool. I have installed gptme with pipx and I have python-playwright installed as a system package (on arch).
Whenever gpt wants to read the web I see this warning:
WARNING:gptme.chat:Browser tool not available, skipping URL read

could you please suggest hiow I can get it working? (have checked docs and code)
thanks in advance!

**Comment by ErikBjare** [comment]
You cannot install playwright from Arch repos, as each version of playwright needs a specific browser version to be installed (with `playwright install chromium`).

We recently locked the playwright version to prevent people from having to download a new browser version on every update.

Try installing gptme with browser extras `pipx install 'gptme[browser]'`, and then run `python -m playwright install` inside the gptme virtualenv managed by pipx. Since this is not straight forward https://github.com/pypa/pipx/issues/434, you can ask gptme to do it (or just do `gptme '/shell python3 -m playwright install'`), since it's in the venv by default.

I will look into making all this smoother.

**Comment by materemias** [comment]
It worked this way, thanks a lot. maybe it would be worth to add these steps to the documentation!

**Comment by ErikBjare** [comment]
Done in #193, thanks for reporting!

**Comment by kfishes** [comment]
I cannot get this to work for the life of me! It acts like it's working but fails to do any actual web browsing
